import './lib/css_msmeawards.css'

import {Header} from './components/header';
import { Footer } from './components/footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
        <Header/>
        {children}
        <Footer/>
    </>
  )
}

